### ISSUE TITLE
Not working even with document-end

### ISSUE THREAD

**Issue by NarryG** [MAT4DOR/op-listing#1]
Title

**Comment by MAT4DOR** [comment]
Hello, I pushed a commit that should fix the issue of the document load. I'm just waiting for a friend to confirm if it works properly.

Please try updating the script: Click the Tampermonkey icon on the browser and go to 'Check for userscript updates'.

If it doesn't work please provide the version of Chrome you are using and the OS.

Thanks for trying this script!
